name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        cibw_python: ["cp310-*" ]
        cibw_arch: ["aarch64"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          # This is needed for now because cffi has no cp310 wheels
          CIBW_BEFORE_ALL_LINUX: "yum -y install libffi-devel"


      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: wheelhouse/*.whl
